[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "EventIdentifier"
version = "0.1.0"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyterlab",
]